"""
Handler for g2_questLogIntoAccount.
Auto-creates accounts on first login.
"""

import uuid
import secrets
import base64
import json
import string
from datetime import datetime, timezone
from pathlib import Path

from config import BASE_DIR, LOG_DIR
from services.db import accounts, bundles
from services.property_defaults import default_for_property

LOGIN_LOG_FILE = LOG_DIR / "login_traffic.log"

# Profile applied to every newly created account. Colours are packed ARGB
# ints (0xAARRGGBB); -16777216 is opaque black.
PROFILE_PATH = Path(BASE_DIR) / "data" / "account_profile.json"


def _credential_shaped(prefix: str, length: int) -> str:
    """
    Build a credential-shaped placeholder.

    The client treats these fields as AWS SigV4 credentials and signs its
    DynamoDB calls with them, but this server issues and accepts them itself,
    so only the shape matters. Generating them at runtime (instead of storing
    literals) keeps real-looking secrets out of version control - GitHub push
    protection rejects any commit containing an ASIA-prefixed key ID.
    """
    alphabet = string.ascii_uppercase + string.digits
    body = "".join(secrets.choice(alphabet) for _ in range(length - len(prefix)))
    return prefix + body


# Stable for the lifetime of the process, so a client that caches them keeps
# working until the server restarts.
ACCESS_KEY = _credential_shaped("ASIA", 20)
SECRET_KEY = _credential_shaped("", 40)


def _load_profile() -> dict:
    """Load the default account profile, ignoring keys that start with '_'."""
    try:
        raw = PROFILE_PATH.read_text(encoding="utf-8")
        return {k: v for k, v in json.loads(raw).items() if not k.startswith("_")}
    except FileNotFoundError:
        print(f"[login] Profile not found at {PROFILE_PATH}, using built-in defaults")
    except Exception as exc:
        print(f"[login] Failed to load profile: {exc}")
    return {}


async def _all_bundle_keys() -> list:
    """Every bundle key in the database, so players own all current bundles."""
    keys = await bundles.distinct("bundleKey")
    return sorted(k for k in keys if isinstance(k, str) and k)


def _server_time() -> str:
    """Current time in the game's format: 'YYYY MM/DD HH:mm:ss'"""
    now = datetime.now(timezone.utc)
    return now.strftime("%Y %m/%d %H:%M:%S")


def _random_session_id() -> str:
    return str(uuid.uuid4().int % 100_000_000)


def _random_nonce() -> str:
    return base64.b64encode(secrets.token_bytes(16)).decode("ascii")


def _random_key(length: int = 48) -> str:
    return base64.b64encode(secrets.token_bytes(length)).decode("ascii")


def _append_login_log(request_body: dict, response_body: dict) -> None:
    """Append login request/response payloads (no headers) to a file."""
    LOGIN_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).isoformat()
    entry = (
        f"[{timestamp}]\n"
        f"RequestBody: {json.dumps(request_body, ensure_ascii=False)}\n"
        f"ResponseBody: {json.dumps(response_body, ensure_ascii=False)}\n"
        f"{'=' * 80}\n"
    )
    with LOGIN_LOG_FILE.open("a", encoding="utf-8") as log_file:
        log_file.write(entry)


# Default account template for new players
DEFAULT_ACCOUNT = {
    "displayName": "<color=blue>920Man</color>",
    "ownedPatterns": ["1x1_stuffed",
      "2x2x2_stuffed",
      "zipperDefault",
      "stuffingDispenser",
      "2x2x2_slope_stuffed",
      "2x2_wooden",
      "1x1_hiderDetector",
      "footballHelmet",
      "1x1_corner_pipe",
      "4x4_wooden",
      "2x4_wooden",
      "1x1_wooden",
      "1x2_wooden",
      "2x4_stuffed",
      "1x4_stuffed",
      "1x2_straight_pipe",
      "1x4_wooden",
      "2x2_trampoline",
      "ninjaHelmet",
      "throwingTeleporter",
      "1x1_straight_pipe",
      "2x2_reinforced",
      "4x4_trampoline",
      "8x8x4_grassRock",
      "16x16x4_grassRock",
      "4x4x4_grassRockUncovered",
      "2x2x2_grassRockUncovered",
      "2x2x2_bush",
      "2x4x2_bush",
      "techWeb",
      "dressingRoom",
      "copyPaster",
      "1x1_basicBomb",
      "throwingBasicBomb",
      "2x2x2_teleporter",
      "basicSweater[black]",
      "1x2_stuffed",
      "2x2x2_wooden",
      "4x4_stuffed",
      "2x2x2_grassRock",
      "2x2x1_grassRock",
      "1x1_6way_pipe",
      "1x1_3way_corner_pipe",
      "paintBrush_brown",
      "2x2_spikes",
      "machete",
      "8x8_spikes",
      "detonator",
      "ninjaHelmetUpgrade",
      "firework",
      "2x2x2_teleporterExit",
      "2x2x2_slope_wooden",
      "paintBrush_red",
      "paintBrush_orange",
      "paintBrush_brown_light",
      "paintBrush_green_dark",
      "paintBrush_brown_dark",
      "paintBrush_purple",
      "4x8x4_bush",
      "paintBrush_yellow_light",
      "paintBrush_red_dark",
      "paintBrush_black",
      "radio",
      "1x1_noteBlock",
      "stuffedCopier",
      "snowball",
      "8x8x4_snowRock",
      "8x8x4_snowRockUncovered",
      "2x2x2_snowRock",
      "2x2x2_snowRockUncovered",
      "16x16x4_snowRock",
      "2x2x1_snowRock",
      "2x2_ice",
      "2x2x1_slope_ice",
      "2x2x2_slope_ice",
      "1x1_freezeBomb",
      "4x4x4_snowRockUncovered",
      "4x4x4_snowRock",
      "16x16x4_snowRockUncovered",
      "2x2x1_snowRockUncovered",
      "paintBrush_blue",
      "paintBrush_white",
      "paintBrush_pink",
      "yeti",
      "freezeGlove_yeti",
      "throwingFreezeBomb",
      "freezeGlove",
      "8x8_ice",
      "paintBrush_blue_light",
      "paintBrush_cyan_light",
      "paintBrush_cyan",
      "paintBrush_cyan_emissive",
      "1x1x2_arrowSign_forward",
      "1x1x2_arrowSign_forward45",
      "1x1x2_arrowSign_up",
      "1x1x2_arrowSign_up45",
      "hotCoco",
      "decoration_snow_pillar0",
      "decoration_snow_icicle2",
      "decoration_snow_pillar1",
      "decoration_snow_icicle0",
      "decoration_snow_snowman0",
      "decoration_snow_arch0",
      "decoration_snow_icicle1",
      "1x2_icicleTrap",
      "4x4_fan",
      "cosmeticsStore",
      "4x4_reinforced",
      "frisbee",
      "knightHelmet",
      "basicSweater[yellow]",
      "zipperMobilePhone",
      "creatorPack_items",
      "creatorPack_cosmetics",
      "throwingMegaphone",
      "paintBrush_blue_dark",
      "starGlasses",
      "basicSweater[blue_light]",
      "2x16_wooden",
      "1x8_wooden",
      "2x2x1_slope_wooden",
      "2x8_wooden",
      "8x8_wooden",
      "4x8_wooden",
      "paintBrush_yellow_emissive",
      "umbrellaGlider",
      "throwingDecoy",
      "knightHelmetUpgrade",
      "microphonePitchUp",
      "microphonePitchDown",
      "microphone",
      "4x4_bouncePad",
      "1x1_drum",
      "noCopySign",
      "microphoneCursed",
      "groundLevelShifter",
      "footballHelmetUpgrade",
      "basicLongShirt[purple]",
      "snowExplorer",
      "1x1_hiderDetector_radar",
      "1x1x2_ziplinePylon",
      "grapplingHook",
      "raceStart",
      "raceFinish",
      "4x8_raceCheckpoint",
      "6x6_raceCheckpoint",
      "1x1x4_raceCheckpoint",
      "2x2x2_slope_cornerOut_wooden",
      "2x2x2_slope_cornerIn_wooden",
      "1x2x2_slope_wooden",
      "1x2x1_slope_wooden",
      "1x1x2_slope_cornerOut_wooden",
      "1x1x2_slope_cornerIn_wooden",
      "2x2x1_slope_cornerIn_wooden",
      "2x2x1_slope_cornerOut_wooden",
      "1x1_straight_pipeFat",
      "1x2_straight_pipeFat",
      "1x1_corner_pipeFat",
      "1x1_3way_pipeFat",
      "1x1_3way_corner_pipeFat",
      "1x1_4way_pipeFat",
      "1x1_5way_pipeFat",
      "1x1_3way_pipeJunction",
      "1x1_4way_pipeJunction",
      "1x1_4way_corner_pipeJunction",
      "1x1_6way_pipeFat",
      "1x1_4way_corner_pipeFat",
      "pelletGun",
      "gameModeSign_hangout",
      "rose",
      "throwingImpulseBomb",
      "hairBoy6[brown_dark]",
      "zipperAvatar",
      "1x1_stuffingStorage",
      "paintBrush_orange_emissive",
      "paintBrush_green_emissive",
      "4x4x4_remoteStuffingDispenser",
      "mapRotator",
      "1x1_4way_pipe",
      "decoration_suburb_flower0",
      "decoration_suburb_flower1",
      "buttjo",
      "farmerChicken",
      "cheeseHat",
      "frenchHat",
      "circleGlasses",
      "basicHoodie[red]",
      "1x1_impulseBomb",
      "throwingSmokeBomb",
      "1x1_smokeBomb",
      "4x4x4_grassRock",
      "8x8x4_grassRockUncovered",
      "16x16x4_grassRockUncovered",
      "2x2x1_grassRockUncovered",
      "1x1_3way_pipe",
      "1x1_5way_pipe",
      "1x1_4way_corner_pipe",
      "1x1_half_pipe",
      "decoration_suburb_mushroom0",
      "decoration_suburb_pillar0",
      "decoration_suburb_gnome0",
      "decoration_suburb_flower2",
      "decoration_suburb_pillar1",
      "decoration_suburb_arch0",
      "mapShifter",
      "1x2_stuffingPlant",
      "4x4_springPad",
      "2x2_springPad",
      "targetDummy",
      "farmer",
      "chef",
      "takeoutBoxHat",
      "mushroomHat",
      "sigma",
      "headphonesHeadCat",
      "basicLongShirt[green_light]",
      "firefighter",
      "basicHoodie[orange]",
      "catHat",
      "constructionConeHat",
      "bananaSplit",
      "basicLongShirt[pink]",
      "snowboarder",
      "polarBear",
      "basicLongShirt[blue_light]",
      "graduationGown",
      "2x1x3_statue_appLab",
      "throwingPillowBomb",
      "2x2_boostPad",
      "2x2x1_slope_boostPad",
      "2x2x2_slope_boostPad",
      "sled",
      "2x2x1_slopeReverse_boostPad",
      "2x2_omniBoostPad",
      "zipperAppLab",
      "fox",
      "police",
      "contentCreatorJune2024",
      "zipperGodsOfGravityShip",
      "basicPuffedShirt[pink]",
      "basicSweatPants[brown]",
      "confettiGun",
      "1x1x2_confettiCannon",
      "1x1_partyButton",
      "1x1_woodenHiderDetector",
      "2x2_disintegratingBlock",
      "partySuit",
      "sparkler",
      "partyHat",
      "doctor",
      "basicHoodie[green_light]",
      "hairGirl5[pink]",
      "basicPoloShirt[white]",
      "zipperTheJeff",
      "hairGirl5[purple]",
      "hairBoy8[purple]",
      "basicShirt[blue]",
      "pizzaBoxHat",
      "skiMaskHat",
      "innerTube",
      "2x2x1_sand",
      "2x2_glass",
      "4x4_glass",
      "4x6_glass",
      "flipper",
      "wristPropellor",
      "1x2_bush",
      "4x4x4_sand",
      "paintBrush_lavender",
      "16x16x4_sand",
      "8x8x4_sand",
      "paintBrush_mocha",
      "paintBrush_blurple",
      "paintBrush_yellow",
      "pirateCaptain",
      "pelletGun_pirate",
      "paintBrush_mocha_light",
      "paintBrush_olive",
      "paintBrush_olive_light",
      "paintBrush_purple_light",
      "paintBrush_purple_emissive",
      "8x8_glass",
      "1x2_glass",
      "2x4_glass",
      "2x2x1_beachRock",
      "2x2x2_beachRock",
      "16x16x4_beachRock",
      "8x8x4_beachRock",
      "4x4x4_beachRock",
      "2x2x2_sand",
      "2x2_flowingWater",
      "8x8_flowingWater",
      "2x2x2_slope_flowingWater",
      "2x2x1_slope_flowingWater",
      "2x2x1_slopeReverse_flowingWater",
      "anchor",
      "1x2_beachBush",
      "4x8x4_beachBush",
      "2x2x2_beachBush",
      "2x4x2_beachBush",
      "decoration_beach_pillar0",
      "decoration_beach_pillar1",
      "decoration_beach_coral0",
      "decoration_beach_clam0",
      "decoration_beach_starfish0",
      "liquidLevelShifter",
      "liquidPainter",
      "decoration_beach_crab0",
      "decoration_beach_coral1",
      "decoration_beach_pillar2",
      "decoration_beach_arch0",
      "decoration_beach_coral2",
      "woodenCannon",
      "surfboard",
      "stuffedCannon",
      "basicPoloShirt[blue]",
      "itemRestrictionsConsole",
      "4x4_glassBrittle",
      "2x4_glassBrittle",
      "1x1_straight_wire",
      "1x1_3way_corner_wire",
      "pulseButton_large",
      "alwaysPowering",
      "pulseExtender",
      "pulseDelay",
      "pulseDelay_small",
      "1x1_4way_wire",
      "1x1_corner_wire",
      "pulseButton_small",
      "1x2_straight_wire",
      "1x1_corner_hiddenWire",
      "1x2_straight_hiddenWire",
      "4x4_trappedWood",
      "1x1_4way_corner_wire",
      "1x1_6way_wire",
      "decoration_researchFacility_radioactiveSymbol0",
      "decoration_researchFacility_radioactiveSymbol1",
      "1x1_radiationBomb",
      "throwingRadiationBomb",
      "1x1_3way_wire",
      "1x1_5way_wire",
      "pulseDelay_big",
      "pulseExtender_big",
      "1x8_straight_wire",
      "8x8_trappedWood",
      "1x1_straight_hiddenWire",
      "2x2_straight_hiddenWire",
      "4x4_door_hidden",
      "logicGate_and",
      "2x2_trappedWood",
      "1x1_trappedWood",
      "4x8_door_hidden",
      "1x1x2_wirelessTransmitter",
      "1x1x2_wirelessReceiver",
      "logicGate_or",
      "4x2_door_hidden",
      "2x2_door_hidden",
      "logicGate_not",
      "logicGate_xor",
      "flipFlop",
      "randomizer",
      "decoration_researchFacility_barrel",
      "1x1_forbidden_steeringWheel",
      "2x2x2_teleporter_powered",
      "candyExplosive",
      "decoration_halloween_pumpkin0",
      "decoration_halloween_jackOLantern0",
      "voodoo",
      "snowball_skull",
      "grimReaper",
      "chicken",
      "1x1_screamingSkull",
      "zipperChicken",
      "candyFreeze",
      "zipperPumpkin",
      "jackOLanternShirtBody",
      "decoration_halloween_gnome4",
      "gameModeSign_monster",
      "2x2x2_stuffedPumpkin",
      "1x1x2_pipeOrganBlock",
      "1x1x2_redEyedGnome",
      "candySpeed",
      "jackOLanternShirtSleeves",
      "2x2_prisonBars",
      "decoration_halloween_gnome0",
      "decoration_halloween_gnome1",
      "paintBrush_gray",
      "paintBrush_gray_dark",
      "paintBrush_red_emissive",
      "throwingPumpkinBomb",
      "2x2_web",
      "zipper100k",
      "candyStuffing",
      "jackOLanternHead",
      "2x2x2_slope_web",
      "decoration_halloween_tombstone0",
      "4x4_web",
      "jackOLanternJacketBody",
      "candyRainbow",
      "decoration_halloween_spider0",
      "jackOLanternJacketSleeves",
      "1x1_pumpkinBomb",
      "jackOLanternJacketCollar",
      "2x2_glassBrittle",
      "decoration_halloween_gnome2",
      "contentCreatorOctober2024",
      "witchesBroom",
      "explosiveGrenade",
      "smokeGrenade",
      "impulseGrenade",
      "shield",
      "2x2x2_teleporterExit_powered",
      "2x2x2_teleporterDeath",
      "2x2x2_teleporterRecall",
      "resetMapBlock",
      "crossbow",
      "1x1_slab2_wooden",
      "2x2_slab2_wooden",
      "2x2_slab4_wooden",
      "1x1_slab4_wooden",
      "endRoundEarlyButton",
      "8x8_door_hidden",
      "noKnockbackProtectionSign",
      "healthModeSign",
      "4x4_playerGate_pulse",
      "2x2_playerGate_maxStuffing",
      "2x2_playerGate_revive",
      "4x4_playerGate_maxStuffing",
      "4x4_playerGate_revive",
      "1x1_3way_hiddenWire",
      "decoration_researchFacility_hazmat",
      "gameModeSign_hideAndSeek",
      "gameModeSign_tag",
      "gameModeSign_arenaFFA",
      "2x2_playerGate_pulse",
      "pulseButton_stuffingCost",
      "4x4_door_verticalLines",
      "4x8_door_verticalLines",
      "keyDispenser",
      "2x2_springPad_powered",
      "2x2_screen",
      "4x4_door_horizontalLines",
      "4x8_door_horizontalLines",
      "machete_spartan",
      "spartan",
      "2x2x2_teleporterDeath_powered",
      "1x1x2_confettiCannon_powered",
      "2x2_spikes_powered",
      "8x8_spikes_powered",
      "4x4_springPad_powered",
      "pulseKeyhole",
      "itemDispenser",
      "1x1_screen",
      "1x1_computer",
      "1x1_lightBulb",
      "4x4_screen",
      "1x1x2_textSign",
      "1x1_textSign",
      "4x4_door_barred",
      "2x2_door_grate",
      "4x8_door_keyhole",
      "4x4_door_keyhole",
      "sittingTurkeyHat",
      "hairFacial2[yellow_light]",
      "contentCreatorNovember2024",
      "pulseButton_staff",
      "RCToyRemote",
      "decoration_christmas_gnome1",
      "elfShirtBody",
      "decoration_christmas_ornament0",
      "decoration_christmas_gnome0",
      "coal",
      "handBell",
      "santa",
      "giftBox",
      "1x1_bell",
      "elfShirtSleeves",
      "decoration_christmas_ornament1",
      "plushYP1C3",
      "plushYP1C2",
      "plushYP1C1",
      "letter",
      "1x1_hoHoHoBlock",
      "windupBomb",
      "1x1_ziplinePylon_lightsYellow",
      "decoration_christmas_reindeer0",
      "decoration_christmas_gnome2",
      "elfOveralls",
      "decoration_christmas_ornament2",
      "RCAdvancedCar_blue",
      "wristRCToyRemote",
      "2x2x2_stuffedPresent",
      "decoration_christmas_wreath0",
      "throwingSnowflake",
      "1x1_ziplinePylon_lightsHoliday",
      "snowMachine",
      "elfHat",
      "1x1_coalFurnace",
      "elfEars",
      "RCTrain",
      "presentStackHat",
      "zipperWishlist",
      "devonMask",
      "2x2_spikesFull",
      "8x8_spikesFull",
      "stuffedAutoTurret",
      "woodenAutoTurret",
      "pelletSniper",
      "missile",
      "itemCannon",
      "techWeb_gameModes",
      "gameModeSign_hangoutTeams",
      "teamDefinitionSign",
      "balanceTeamsButton",
      "2x2_playerGate_joinLeastPopulatedTeam",
      "friendlyFireSign",
      "4x4_playerGate_joinTeam",
      "pulseButton_joinTeam",
      "pulseButton_leaveTeam",
      "4x4_playerGate_joinLeastPopulatedTeam",
      "4x4_teamBarrier",
      "2x2_teamBarrier",
      "16x16_teamBarrier",
      "sergeant",
      "pelletGun_army",
      "gameModeSign_arenaTeams",
      "2x2x2_teleporter_staff",
      "pulseButton_team",
      "2x2x2_teleporter_team",
      "4x4_playerGate_leaveTeam",
      "2x2_playerGate_leaveTeam",
      "2x2_playerGate_joinTeam",
      "8x8_teamBarrier",
      "godsOfGravityDefaultHat",
      "godsOfGravityHat",
      "hairGirl5[purple_light]",
      "hairGirl5[green]",
      "hairBoy6[black]",
      "damageMultiplierSign",
      "teamPlayerLimitSign",
      "noTimeLimitSign",
      "maxStuffingCountSign",
      "noStuffingRefundsSign",
      "teamWinBlock",
      "16x16_teamBuildPlate",
      "4x4_teamBuildPlate",
      "8x8_teamBuildPlate",
      "pelletShotgun",
      "bazooka",
      "RCHandCamera",
      "commando",
      "explosiveGrenade_frag",
      "FPVGoggles",
      "RCBiplane",
      "hairGirl5[black]",
      "basicSweater[teal]",
      "hairGirl5[red]",
      "hairGirl5[cyan]",
      "scarfWinter",
      "hairBoy6[red]",
      "potion",
      "2x2_worldMap",
      "1x1_ingredientSpawner_mushroom",
      "1x1_ingredientSpawner_flowerEvil",
      "1x1_ingredientSpawner_flowerGood",
      "2x2x2_cauldron",
      "1x1_ingredientSpawner_berries",
      "1x1_ingredientSpawner_leaf",
      "1x1_ingredientSpawner_tentacle",
      "potion_speed",
      "potion_haste",
      "potion_slowFalling",
      "potion_love",
      "knightArmor",
      "shield_knight",
      "potionTeamInfuser",
      "potion_poison",
      "potion_blindness",
      "1x1_ingredientSpawner_feather",
      "1x1_ingredientSpawner_bone",
      "1x1_ingredientSpawner_eyeball",
      "8x8x4_fantasyRock",
      "8x8x4_fantasyRockUncovered",
      "2x2x2_fantasyRock",
      "2x2x1_fantasyRock",
      "2x2x1_fantasyRockUncovered",
      "16x16x4_fantasyRockUncovered",
      "16x16x4_fantasyRock",
      "2x2x2_fantasyRockUncovered",
      "4x4x4_fantasyRock",
      "4x4x4_fantasyRockUncovered",
      "arrow",
      "grapplingArrow",
      "decoration_fantasy_pillar0",
      "decoration_fantasy_pillar1",
      "decoration_fantasy_arch0",
      "decoration_fantasy_rock0",
      "4x4_door_portcullis",
      "8x8_door_portcullis",
      "paintBrush_blue_turquoise",
      "paintBrush_green",
      "paintBrush_teal",
      "paintBrush_purple_dark",
      "paintBrush_periwinkle",
      "paintBrush_purple_dark_emissive",
      "dagger",
      "1x1_slope_wooden",
      "1x1x0.5_slope_wooden",
      "1x1_slope_cornerIn_wooden",
      "1x1x0.5_slope_cornerOut_wooden",
      "1x1x0.5_slope_cornerIn_wooden",
      "1x1_slope_cornerOut_wooden",
      "decoration_fantasy_mushroom1",
      "decoration_fantasy_mushroom2",
      "1x1_ingredientSpawner_tail",
      "pet_chicken_yellow_orange",
      "tennisBall",
      "petNametag",
      "pet_cat_red_red_dark",
      "petBrush",
      "pet_chicken_blue_yellow",
      "petLaserPointer",
      "pet_cat_pink_red",
      "pet_dog_green_light_blue_turquoise",
      "pet_cat_cyan_light_blue_turquoise",
      "2x2_appLabPie",
      "pet_dog_brown_dark_black",
      "pet_chicken_green_light_green_dark",
      "druid",
      "umbrellaGlider_leaf",
      "pet_chicken_mocha_brown_dark",
      "pet_dog_yellow_orange",
      "pet_chicken_blue_light_blue",
      "pet_chicken_purple_periwinkle",
      "pet_cat_yellow_light_orange",
      "pet_dog_red_red_dark",
      "pet_cat_green_light_green",
      "pet_dog_blue_light_blue",
      "pet_dog_orange_light_mocha",
      "pet_dog_mocha_light_brown_dark",
      "pet_chicken_blue_turquoise_cyan_light",
      "pet_cat_orange_orange_light",
      "pet_cat_blue_light_blue",
      "pet_cat_lavender_purple_light",
      "pet_dog_gray_blue_dark",
      "pet_dog_lavender_purple",
      "pet_chicken_orange_blue_light",
      "pet_dog_pink_red",
      "pet_rat_blue_dark_pink",
      "pet_pig_green_light_green",
      "godsOfGravityProductionHat",
      "godsOfGravityConquestHat",
      "godsOfGravityVolatilityHat",
      "godsOfGravityTeleportationHat",
      "godsOfGravityStealthHat",
      "godsOfGravityDefenseHat",
      "godsOfGravityDestructionHat",
      "pet_cat_brown_brown_dark",
      "techWeb_prop",
      "prop_wetFloorSign",
      "prop_lawnChair",
      "prop_schoolDesk",
      "prop_wallClock",
      "prop_whippedCream",
      "prop_toilet",
      "gameModeSign_propHunt",
      "spy",
      "dagger_spy",
      "propSelector",
      "pet_sheep_blue_dark_gray",
      "pet_pig_pink_purple_light",
      "pet_sheep_blue_blue_light",
      "1x1_ingredientSpawner_flour",
      "1x1_ingredientSpawner_egg",
      "1x1_ingredientSpawner_milk",
      "1x1_ingredientSpawner_sugar",
      "1x1_ingredientSpawner_lettuce",
      "1x1_ingredientSpawner_fruit",
      "1x1_ingredientSpawner_tomato",
      "1x1_ingredientSpawner_potato",
      "1x1_ingredientSpawner_beef",
      "1x1_ingredientSpawner_chicken",
      "1x1_ingredientSpawner_noodle",
      "2x2x2_stove",
      "2x2x2_oven",
      "1x1_ingredientSpawner_bacon",
      "achievementsConsole",
      "pet_chicken_pink_lavender",
      "petStopSign",
      "redRidingHood",
      "8x2x1_slope_wooden",
      "8x2x2_slope_wooden",
      "prop_rubberDuck",
      "teamDefinitionSign_hider",
      "teamDefinitionSign_seeker",
      "VIPConsole",
      "pulseButton_vip",
      "2x2x2_teleporter_vip",
      "gameModeSign_infection",
      "noResetMapSign",
      "roundDurationSign",
      "noPropsDrainStuffingSign",
      "4x4_worldMap",
      "petCrown",
      "pet_bunny_brown_dark_pink",
      "decoration_fantasy_mushroom3",
      "decoration_fantasy_frog1",
      "1x2_handhold",
      "saddle",
      "pet_platypus_blue_turquoise_orange",
      "drumstick",
      "2x2_speaker",
      "4x4_speaker",
      "record_suburbTheme",
      "techno",
      "buttjo_techno",
      "1x1x2_recordPlayer",
      "recordDisplay",
      "warHorn",
      "discLauncher",
      "1x1_speaker",
      "1x1_tapePlayer",
      "1x1_audioLowPassEffect",
      "1x1_audioReverbEffect",
      "soundboard",
      "techWeb_music",
      "fireburst_golden",
      "RSLatch",
      "2x2x2_diverter",
      "2x2_door_verticalLines",
      "itemAccepter",
      "textBroadcaster",
      "1x1_soundTap",
      "regionalCopyPaster",
      "DLatch",
      "voteBroadcaster",
      "chainsaw",
      "fireburst",
      "record_oceanTheme",
      "noHiderHintsSign",
      "noRandomSeekerSelectionSign",
      "prop_cog",
      "prop_colorfulFlower",
      "prop_vendingMachine",
      "record_tag",
      "hungryHippo",
      "2x2x2_funnel",
      "1x1_healthPackSmall",
      "1x1_healthPackLarge",
      "healingGun",
      "1x1_stuffedLandmine",
      "mobSpawnEgg_insectSoldier",
      "mobSpawnEgg_insectExploder",
      "2x2x2_mobSpawner_singleton",
      "2x2x2_mobSpawner_multi",
      "potionCannon",
      "record_snowTheme",
      "1x8_handhold_pole",
      "1x1_handhold",
      "1x4_handhold_pole",
      "1x1_corner_handhold_pole",
      "1x2_handhold_pole",
      "1x1_ingredientSpawner_mushroomLong",
      "exterminator",
      "pelletShotgun_exterminator",
      "lootSack",
      "wristAirBlaster",
      "zipper20",
      "sawbladeLauncher",
      "spear",
      "wristVacuum",
      "terrainRandomizer",
      "terrainCopyPaster",
      "terrainShaper",
      "basicShirt[red]",
      "basicShirt[yellow]",
      "terrainMaterialPaintBrush_grass",
      "terrainDecoration_suburb_tree0",
      "terrainDecoration_suburb_tree2",
      "terrainDecoration_suburb_tree1",
      "terrainDecoration_suburb_log0",
      "terrainDecoration_suburb_bush1",
      "terrainDecoration_suburb_bush0",
      "npcSpawner_gnome_suburb_0",
      "compass",
      "boxingGlove",
      "mobSpawnEgg_grazingYak",
      "1x1_landmine",
      "1x1_woodenBasicBomb",
      "woodenMissileTurret",
      "stuffedMissileTurret",
      "autoTurretTargeter",
      "terrainMaterialPaintBrush_sand",
      "discordHat",
      "mace",
      "mobSpawnEgg_insectTank",
      "match",
      "2x2x1_sandstone",
      "16x16x4_sandstone",
      "2x2x2_sandstone",
      "4x4x4_sandstone",
      "minecart",
      "1x1_corner_railStuffed",
      "1x4_straight_railStuffed",
      "fireExtinguisher",
      "1x1_slope_railStuffed",
      "smokeDetector",
      "boomerang",
      "roomPassageway_grassRock",
      "terrainMaterialPaintBrush_sandstone",
      "paintBrush_maroon",
      "paintBrush_orange_light",
      "2x2x1_sandDune",
      "8x8x4_sandstone",
      "2x2x2_sandDune",
      "16x16x4_sandDune",
      "4x4x4_sandDune",
      "terrainMaterialPaintBrush_sandstoneDark",
      "terrainMaterialPaintBrush_sandDune",
      "8x8x4_sandDune",
      "paintBrush_maroon_dark",
      "paintBrush_green_light",
      "paintBrush_beige",
      "paintBrush_guac",
      "decoration_desert_pillar0",
      "playerListBlock",
      "npcSpawner_gnome_halloween_pumpkin",
      "jackInTheBox",
      "candyFire",
      "terrainDecoration_halloween_pumpkin1",
      "1x1_ingredientSpawner_pumpkin",
      "terrainDecoration_halloween_pumpkin0",
      "record_halloweenTheme",
      "terrainDecoration_halloween_tombstone0",
      "candyBlindness",
      "8x8_brick",
      "4x8_brick",
      "4x4_brick",
      "soundboard_halloween",
      "helmetFlashlight",
      "1x1_bearTrap",
      "1x1_lostNoteSpawner",
      "npcSpawner_gnome_halloween_mummy",
      "npcSpawner_gnome_halloween_witch",
      "candyFeign",
      "1x1_woodenPumpkinBomb",
      "scythe",
      "1x1x2_stuffedTrophie_horror",
      "1x1_candyBowl",
      "stuffedFlashlight",
      "npcSpawner_gnome_halloween_trickOrTreat",
      "prop_parkingMeter",
      "prop_stool",
      "basketball",
      "football",
      "baseball",
      "baseballBat",
      "fieldGoal",
      "basketballHoop",
      "autoPitcher",
      "terrainDecoration_suburb_house1",
      "terrainDecoration_suburb_house2",
      "terrainDecoration_suburb_house0",
      "navigationSignpostBlock",
      "mobSpawnEgg_bitingBat",
      "stuffedSawbladeTurret",
      "variableDefinition",
      "variableSetConstant",
      "variableCompareGreaterThan",
      "variableSetRandom",
      "2x2_variableDisplay",
      "variableCompareEqualTo",
      "variableCompareLessThan",
      "variableIsGreatest",
      "4x4_variableDisplay",
      "4x2_variableDisplay",
      "8x4_variableDisplay",
      "4x2_variableTimeDisplay",
      "8x4_variableTimeDisplay",
      "daylightSensor",
      "customLightingSelector",
      "prop_microwave",
      "dragonEgg_green",
      "dragonEgg_black",
      "dragonEgg_purple",
      "4x4_stuffedPetArena",
      "contentCreatorOctober2025",
      "cyberDragonWings",
      "flareGun_dragon",
      "petBackflipSign",
      "pet_dragon_purple_yellow",
      "pet_dragon_green_light_green_dark",
      "pet_dragon_purple_dark_red",
      "roomPassageway_wooden",
      "npcSpawner_gnome_snow_0",
      "gameModeSign_outlaw",
      "paintBrush_yellow_dark_emissive",
      "4x4_warpPortal",
      "itemCustomizationBench",
      "itemRecolorer",
      "techWeb_decorations",
      "prop_ceilingLight",
      "krampus",
      "bazooka_krampus",
      "record_holidayTheme",
      "1x1_fireBomb",
      "fireGrenade",
      "fireAxe",
      "RCTank",
      "1x1_itemDecorationSpawner_CandyCane",
      "teamBubbleSetter",
      "gingerbreadBody",
      "npcSpawner_gnome_christmas_elf",
      "terrainDecoration_holiday_candyCane",
      "gingerbreadSleeves",
      "1x1_itemDecorationSpawner_Peppermint",
      "skater",
      "sled_skateboard",
      "snowGlobe",
      "2x2_snowPile",
      "prop_astronautHelmet",
      "toymakerSanta",
      "RCBiplane_sleigh",
      "gingerbreadBackpack",
      "candyCaneHook",
      "1x1_mistletoe",
      "gingerbreadHead",
      "freezeRay",
      "christmasTitleBelt",
      "loafMask",
      "zipperYeepToymaker",
      "terrainDecoration_block_2x2x8",
      "terrainDecoration_block_8x2x8",
      "terrainDecoration_block_16x2x16",
      "terrainDecoration_block_2x2x2",
      "8x8_glassOneWay",
      "4x6_glassBrittle",
      "2x4_glassOneWay",
      "4x4_glassOneWay",
      "2x2_glassOneWay",
      "prop_movingBoxClosed",
      "weatherBlock_fog",
      "weatherBlock_thunderstorm",
      "weatherBlock_rain",
      "weatherBlock_snow",
      "weatherBlock_blizzard",
      "noItemsSign",
      "ceilingCollisionSign",
      "4x4_mobBarrier",
      "16x16_mobBarrier",
      "mobDamageMultiplierSign",
      "noMobRaidsSign",
      "1x1_itemDecorationSpawner_CardboardRightTriangle",
      "1x1_itemDecorationSpawner_CardboardStar",
      "banner",
      "balloon",
      "2x2_cloudBlock",
      "1x1_propeller",
      "6x6_boostRing",
      "6x6_stuffingRing",
      "airGrabber",
      "wristWing",
      "prop_radio",
      "4x4_cloudBlock",
      "touchKillsPlayersSign",
      "worldFuelConsoleBlock",
      "4x4x4_remoteStuffingDispenser_teamOnly",
      "itemRestrictionsConsole_team",
      "mobDeathTracker",
      "2x2_mobBarrier",
      "8x8_mobBarrier",
      "2x2_mobSpawner_zone",
      "gameModeSign_survival",
      "2x2x2_mobLure",
      "proximityChatSign",
      "4x4_petArena",
      "petStore",
      "globalPetStopSign",
      "flyingPetRidingSign",
      "1x1_petBed",
      "pet_fox_cyan_light_green_dark",
      "ugHat",
      "prop_sodaCan",
      "steampunkAviator",
      "crossbow_steampunk",
      "wristWing_angel",
      "wristWing_demon",
      "pet_dino_cyan_blue_turquoise",
      "contentCreatorDecember2025",
      "2x2x2_slope_pyramid_wooden",
      "1x1x0.5_slope_pyramid_wooden",
      "2x2x2_slope_cornerPyramid_wooden",
      "2x2x1_slope_pyramid_wooden",
      "1x1_slope_pyramid_wooden",
      "1x1x0.5_slope_cornerPyramid_wooden",
      "2x2x1_slope_cornerPyramid_wooden",
      "1x1x2_slope_cornerPyramid_wooden",
      "1x1_slope_cornerPyramid_wooden",
      "1x1x2_slope_pyramid_wooden",
      "roomPassageway_sandstone",
      "1x4_slab2_wooden",
      "1x4_slab4_wooden",
      "1x1_stair2_wooden",
      "1x4_stair2_wooden",
      "1x8_slab2_wooden",
      "1x8_slab4_wooden",
      "1x4_slab43_wooden",
      "1x8_slab43_wooden",
      "1x1_slab2_half_wooden",
      "1x1_stair2_cornerIn_wooden",
      "1x1_stair2_cornerOut_wooden",
      "onStart",
      "wiringClockPulse",
      "closeServerBlock",
      "1x2_textSign",
      "16x16_screen",
      "npcSpawner_gnome_hazmat_0",
      "2x2_door_sliding",
      "4x4_door_sliding",
      "mobSpawnEgg_rat",
      "4x4_clock",
      "mobSpawnEgg_ratKing",
      "RCFighterJet",
      "6x6_boostRing_directional",
      "prop_trafficLight",
      "prop_laptop",
      "record_lightsOut",
      "record_featherLight",
      "fishingRod_basic",
      "fishBucket",
      "fishingRod_intermediate",
      "stuffedFishCatalog",
      "fishingRod_advanced",
      "toyStore",
      "toyLoader",
      "4x4_handleDoor",
      "itemCustomizationEarningsConsole",
      "bannerDisplay",
      "itemDisplay_pedestalShort",
      "1x1_itemDecorationSpawner_Cardboard3DSpike",
      "1x1_itemSpawner",
      "contentCreatorJanuary2026",
      "4x4_carpet",
      "4x8_carpet",
      "8x8_carpet",
      "prop_popcorn",
      "baitTrader",
      "fishDisplay",
      "woodenFishCatalog",
      "1x1_alarmSpeaker",
      "crabCage",
      "2x2_stuffedNavalMine",
      "techWeb_world",
      "2x2_playerGate_worldTokenSet",
      "4x4_playerGate_worldTokenSet",
      "pulseButton_worldTokenSet",
      "tokenBroadcasterTeam_worldTokenSet",
      "tokenBroadcasterTeam_worldTokenAdd",
      "pulseButton_worldTokenCost",
      "pulseButton_worldTokenThreshold",
      "poseidon",
      "spear_trident",
      "tokenDailyReward",
      "tokenTimeBoundReward",
      "tokenTrigger_playerDeath",
      "tokenTrigger_playerKill",
      "tokenTrigger_playerWin",
      "tokenTrigger_mobDeath",
      "itemAccepter_worldTokenAdd",
      "tokenExchanger",
      "2x2x2_teleporter_worldTokenThreshold",
      "maxTokensSign",
      "2x2_vipBarrier",
      "4x4_vipBarrier",
      "8x8_vipBarrier",
      "worldTokenDisplay",
      "4x4_tokenBarrier",
      "8x8_tokenBarrier",
      "2x2_tokenBarrier",
      "worldTokenLeaderboard",
      "1x1_audioSpeedUpEffect",
      "1x1_audioSlowDownEffect",
      "1x1x2_recordPlayerBroadcaster",
      "2x2_navalMine",
      "harpoon",
      "harpoonGun",
      "1x1_plushPad",
      "plushBatProxy",
      "plushStickyImpulseBombProxy",
      "plushFrisbeeProxy",
      "plushSleepCapProxy_blue",
      "plushSleepCapProxy_red",
      "prop_2x2painting3",
      "mobSpawnEgg_horrorGrandma",
      "prop_2x3painting2",
      "1x1_rivetedMetal",
      "prop_bookCluster",
      "prop_2x2painting0",
      "prop_largeChandelier",
      "prop_2x2painting1",
      "prop_woodenBed",
      "4x4_hardwoodFloor",
      "4x4_wallpaper0",
      "prop_wallCandleSingle",
      "2x2_carpet",
      "1x4_carpet",
      "1x1_carpet",
      "prop_wallCandleDouble",
      "4x8_hardwoodFloor",
      "1x1_localKeySpawner_crescent",
      "1x1_localKeySpawner_star",
      "4x4_handleDoorLocalKey_threeKey",
      "1x1_localKeySpawner_keyCard",
      "2x4_deadlyWardrobe",
      "4x4_keyCardDoor",
      "prop_fireHydrant",
      "gameModeSign_custom",
      "4x6_teamBarrier",
      "4x4_oneWayBarrier",
      "8x8_oneWayBarrier",
      "4x6_oneWayBarrier",
      "pumaHoodie_black",
      "pumaHoodie_white",
      "1x1_itemDecorationSpawner_PUMAText",
      "1x1_itemDecorationSpawner_PUMACat",
      "prop_pumaShoeBox",
      "prop_sock",
      "pumaShoeLauncher",
      "pumaTracksuit[blue]",
      "prop_footprintRight",
      "prop_footprintLeft",
      "pumaBucketHat_red",
      "pumaBucketHat_purple",
      "flail",
      "pumaShoe_9",
      "pumaShoe_6",
      "pumaShoe_11",
      "pumaShoe_1",
      "pumaShoe_5",
      "pumaShoe_7",
      "pumaShoe_17",
      "pumaShoe_0",
      "pumaShoe_18",
      "zipperMusicPie",
      "woodenSawbladeTrap",
      "1x1_healthPackLarge_teamOnly",
      "2x2x2_campfire",
      "1x1x2_dangerSign",
      "streetStyle",
      "1x1x2_recordPlayerStuffed_boomBox",
      "pumaTracksuit[teal]",
      "pumaTracksuit[red]",
      "pumaShoeBola",
      "pet_puma_blue_turquoise_yellow",
      "pumaCatEars",
      "pet_puma_blue_light_pink",
      "shoeRack",
      "superPuma",
      "petPumaGoldChain",
      "pumaClaw",
      "flag",
      "flagSpawner",
      "2x2_oneWayBarrier",
      "pumaShoe_19",
      "pumaShoe_14",
      "pumaShoe_10",
      "pumaShoe_4",
      "1x1x2_recordPlayerStuffed",
      "1x1_audioIncreaseGainEffect",
      "1x1_audioEchoEffect",
      "1x1_audioDistortionEffect",
      "1x1_tapePlayerBroadcaster",
      "2x2_danceFloor",
      "4x4_danceFloor",
      "1x1_noteBlockSynth",
      "1x1_noteBlockBass",
      "recordStore",
      "1x1_drumSnare",
      "1x1x2_drumCrash",
      "1x1_drumTom",
      "2x2_drumBass",
      "1x1x2_drumHiHat",
      "itemDisplay_wall",
      "stuffedMiniTurret",
      "2x2_slab43_wooden",
      "1x1_slab43_wooden",
      "stuffedMortarTurret",
      "headTurret",
      "pumaShoe_8",
      "pumaShoe_15",
      "pumaShoe_12",
      "pumaShoe_16",
      "1x1_stuffedTrophie_youtube100k",
      "8x8_hardwoodFloor",
      "4x8_wallpaper0",
      "2x2_brick",
      "1x1_brick",
      "4x4_rivetedMetal",
      "4x4_checkboardFloor",
      "4x8_rivetedMetal",
      "4x8_checkboardFloor",
      "1x4_rivetedMetal",
      "8x8_checkboardFloor",
      "8x8_rivetedMetal",
      "2x2_rivetedMetal",
      "terrainDecoration_halloween_skull",
      "2x2_checkboardFloor",
      "1x4_checkboardFloor",
      "1x1_checkboardFloor",
      "terrainDecoration_snowHalloween_tree0",
      "4x4_wallpaper2",
      "8x8x4_compactedDirt",
      "4x8_wallpaper2",
      "1x1_wallTrim",
      "4x8_rug1",
      "1x4_wallpaper0",
      "1x1_wallpaper0",
      "4x8_rug0",
      "horrorMobPatrolPoint",
      "2x2_hardwoodFloor",
      "prop_2x2painting2",
      "1x4_hardwoodFloor",
      "4x4_wallpaper1",
      "1x1_hardwoodFloor",
      "4x8_wallpaper1",
      "prop_woodenBanister",
      "1x4_wallpaper2",
      "1x1_wallpaper2",
      "itemSupercharger",
      "prop_monitor",
      "pumaShoe_2",
      "superheroGenericWhiteRed",
      "prop_laundryBasket",
      "prop_waterCooler",
      "1x1_superpowerSpawner_KnockbackMultiplier",
      "1x1_superpowerSpawner_RefundCost",
      "rubberChicken",
      "1x1_whoopeeCushionMine",
      "blankGun",
      "blankPalm",
      "blankWrist",
      "blankHelmet",
      "1x1_superpowerSpawner_DamageMultiplier",
      "1x1_superpowerSpawner_ShootPellet",
      "1x1_superpowerSpawner_ShootFireburst",
      "1x1_superpowerSpawner_ShootSniperBullet",
      "1x1_superpowerSpawner_ShootMiniMissile",
      "1x1_superpowerSpawner_ShootCannonball",
      "1x1_superpowerSpawner_ShootHarpoon",
      "1x1_superpowerSpawner_TrailOrange",
      "1x1_superpowerSpawner_ShootSnowball",
      "1x1_superpowerSpawner_ShootHealingDart",
      "4x4x2_acidVat",
      "wristWebShooter",
      "1x1_superpowerSpawner_ShootFlare",
      "1x1_superpowerSpawner_HoldFire",
      "1x1_superpowerSpawner_HoldLightning",
      "1x1_superpowerSpawner_HoldLaser",
      "lightningHammer",
      "minionCapsule_laser",
      "minionController",
      "1x1_superpowerSpawner_TrailYellow",
      "1x1_superpowerSpawner_TrailGreen",
      "smashGlove",
      "1x1_superpowerSpawner_TrailBlue",
      "1x1_superpowerSpawner_VFXRadiation",
      "1x1_superpowerSpawner_TrailPurple",
      "1x1_superpowerSpawner_SelfPotionRegen",
      "1x1_superpowerSpawner_SelfPotionInvisibility",
      "1x1_superpowerSpawner_VFXSparkle",
      "minionCapsule_lightning",
      "1x1_superpowerSpawner_SelfPotionSlowFalling",
      "1x1_superpowerSpawner_DoubleJump",
      "prop_comicArrow",
      "1x1_superpowerSpawner_Dash",
      "1x1_superpowerSpawner_ChargeFireBall",
      "1x1_superpowerSpawner_ChargePiercingLaser",
      "1x1_superpowerSpawner_ChargeEnergyBall",
      "wristCape",
      "1x1_superpowerSpawner_OrbitalLaser",
      "minionCapsule_energyBall",
      "blankWand",
      "contentCreatorApril2026",
      "prop_trafficCone",
      "woodenFireJet",
      "flameThrower",
      "bullet",
      "revolver",
      "decoration_desert_cactus2",
      "prop_crateOpen",
      "loadoutSetter",
      "record_fleshManor",
      "record_lemonswing",
      "record_hardWired",
      "record_longDays",
      "magnet",
      "4x4_magnetizedBlock",
      "4x4x4_moonRock",
      "8x8x4_moonRock",
      "laserGun",
      "2x2_magnetizedBlock",
      "2x2x2_moonRock",
      "2x2x1_moonRock",
      "throwingBlackHoleBomb",
      "1x1_blackHoleBomb",
      "prop_observationCap",
      "customGravitySelector",
      "gravityZone",
      "1x1_magnetizedBlock",
      "prop_4x4x1_spaceWindow",
      "6x6_door_space",
      "asteroidSpawner_medium",
      "asteroidSpawner_large",
      "1x1_superpowerSpawner_HoldThruster",
      "jetpack",
      "prop_3x5x3_cellTower",
      "prop_2x2x2_statelliteDish",
      "prop_1x4x1_wireAntennae0",
      "gameModeSign_laserTag",
      "wristLaserTagGun",
      "1x4_straight_rail",
      "1x1_fuse",
      "prop_lantern",
      "prop_4x4x1_crater",
      "prop_2x2_moonRocks",
      "paintBrush_gray_cool",
      "paintBrush_amber",
      "paintBrush_rose",
      "paintBrush_gray_cool_light",
      "paintBrush_midnight",
      "paintBrush_cadet",
      "paintBrush_blackhole",
      "paintBrush_blue_emissive",
      "prop_milk",
      "roomPassageway_moonRock",
      "crewTaskList",
      "prop_2x2_moonGeode",
      "prop_1x2_moonGeode",
      "decoration_space_spore0",
      "decoration_space_spore1",
      "tronDisc",
      "2x2_ventOneWay",
      "4x4_tractorBeam",
      "2x2_rift",
      "portalGun",
      "legendaryFishCrown_purple",
      "2x2_grate",
      "tradingCardBinder",
      "cardChallengeBoard",
      "stuffedPlayingCard",
      "cardGun",
      "npcSpawner_gnome_city_1",
      "npcSpawner_frog_suit",
      "2x2_cakeBlock",
      "voteDefinition",
      "ballotBox",
      "1x1_ziplinePylon_flagsAnniversary",
      "1x1_ziplinePylon_flags",
      "stuffedDomino",
      "stuffedDomino45",
      "woodenTradingTable",
      "stuffedTradingTable",
      "wristTradingCardDisplay",
      "record_fantasyTheme",
      "decoration_space_gnome0",
      "record_spaceTheme",
      "decoration_desert_cactus0",
      "puzzlePiece_13",
      "6x1x4_anniversaryPuzzleBoard",
      "puzzlePiece_19",
      "puzzlePiece_6",
      "puzzlePiece_11",
      "puzzlePiece_17",
      "puzzlePiece_31",
      "puzzlePiece_7",
      "puzzlePiece_15",
      "puzzlePiece_18",
      "puzzlePiece_28",
      "puzzlePiece_26",
      "puzzlePiece_22",
      "puzzlePiece_30",
      "puzzlePiece_3",
      "puzzlePiece_9",
      "puzzlePiece_4",
      "puzzlePiece_27",
      "puzzlePiece_1",
      "puzzlePiece_14",
      "puzzlePiece_0",
      "puzzlePiece_23",
      "puzzlePiece_21",
      "puzzlePiece_29",
      "puzzlePiece_10",
      "puzzlePiece_8",
      "puzzlePiece_25",
      "puzzlePiece_5",
      "puzzlePiece_24",
      "puzzlePiece_20",
      "puzzlePiece_16",
      "puzzlePiece_2",
      "stuffedPlayingCard45",
      "puzzlePiece_12",
      "sparkler_ringmaster",
      "anniversary26Hat",
      "anniversaryKeyArt",
      "anniversaryKeyArtLarge",
      "2x2_lightHouseLight",
      "challengeBoard",
      "techWeb_fantasy",
      "techWeb_snow",
      "techWeb_space",
      "techWeb_researchFacility",
      "techWeb_suburb",
      "mobileAppConsole",
      "techWeb_beach",
      "techWeb_desert",
      "publicWorldCodeBlock",
      "flySwatter",
      "balloon_anniversary",
      "grapplingHook_golden",
      "zipperPuzzle",
      "task_pushButton_small_horizontal",
      "task_pushButton_small",
      "task_itemAccepter",
      "crewTasksControlBlock",
      "task_pullCord",
      "task_swipeCard",
      "task_scanPlate",
      "task_target",
      "decoration_desert_cactus1",
      "keyArt_3",
      "roleBadge_tester",
      "paintGun",
      "techWeb_paint",
      "paintBrush_plush_blue",
      "paintBrush_plush_peach",
      "paintBrush_plush_purple",
      "2x1x2_canvas",
      "2x2x2_canvas_slope",
      "1x1x1_canvas",
      "2x1x2_canvas_slope",
      "2x1x2_conveyor_belt",
      "2x1x8_conveyor_belt",
      "2x2x2_sloped_conveyor_belt",
      "paintRoomba",
      "meleePaintBrush",
      "graffiti_0",
      "graffiti_1",
      "prop_wetPaint",
      "bulkColorChange",
      "paintJar",
      "prop_sprayCans",
      "prop_paintBucket",
      "sprayCan",
      "paintBomb",
      "graffiti_2",
      "decoration_desert_arch0",
      "roomPassageway_snowRock",
      "terrainMaterialPaintBrush_snow",
      "terrainDecoration_snow_tree1",
      "terrainDecoration_snow_tree0",
      "terrainDecoration_snow_rock1",
      "terrainDecoration_snow_rock0",
      "terrainDecoration_snow_log0",
      "mobSpawnEgg_grazingSheep",
      "mobSpawnEgg_wolf",
      "mobSpawnEgg_yeti",
      "worldTokenPickup",
      "1x1_worldTokenCrate",
      "maxLivesSign",
      "worldTokenLeaderboard_gameMode",
      "2x2_flammableCarpet",
      "lighter",
      "decoration_desert_rock2",
      "roomPassageway_fantasyRock",
      "wearableBackpack_small",
      "holster_small",
      "1x1x2_barbedWire",
      "1x1x4_barbedWire",
      "1x1x1_barbedWire",
      "wearableBackpack_medium",
      "holster_medium",
      "wearableBackpack_large",
      "explosiveArrow",
      "freezeArrow",
      "fireArrow",
      "bowAndArrow",
      "pinGrenade",
      "gatlingGunMagazine",
      "gatlingGun",
      "gameModeSign_impostor",
      "2x2x1_prisonBar_climbable",
      "8x8x1_prisonBar_climbable",
      "taser",
      "4x4x1_prisonBar_climbable",
      "1x1x2_workoutBench",
      "dumbbell",
      "breakDurationSign",
      "maxInitialSeekersSign",
      "noEatingItemsSign",
      "headImaginationSign",
      "2x2x2_teleporterRecall_timedRelease",
      "lootCrateLoadingConsole",
      "lootCrate_military",
      "lootCrate_snow",
      "lootCrate_suburb",
      "lootCrate_beach",
      "lootCrate_fantasy",
      "lootCrate_space",
      "lootCrate_desert",
      "2x2_target",
      "1x1_target",
      "1x1x1_stuffedClaymore",
      "1x1_alarmLight"
],
    "activeCosmetics": ["roleBadge_tester","monsterArms","monsterBody","monsterHead"],
    "ownedBundles": ["bundle_party","bundle_pirate","bundle_hazmat","bundle_halloween2024","bundle_spartan","bundle_holiday2024","bundle_commando","bundle_druid","bundle_techno","bundle_exterminator","bundle_krampus","bundle_toymaker"],
    "wishlist": [],
    "eyeColor": -1,
    "skinColor": 0,
    "mobileCode": "9200",
    "hasCreatorPack": 1,
    "hasUnlockedPrivateRooms": 1,
    "isIsolated": 0,
    "hasPendingMobileLogin": 0,
    "roleKeys": ["alpha","bamWinner","debug","developer","developer_mapMaker","developer_senior","internal","moderator","moderator_junior","moderator_senior","superStar","tester","tester_senior"],
    "currency": 0,
    "redeemedStashIDs": [],
    "cw_admin": ["920MAN"],
    "cw_staff": ["920MAN"],
    "cw_favorites": ["920MAN"],
    "cw_nextCanUseFreeFuelTimestamp": "1970 01/01 00:00:00",
    "analyticEventKeys": [],
    "firstLogin": "",
    "loginStreakFreezeTimestamp": "1970 01/01 00:00:00",
    "hasPendingWarning": 0,
    "shouldForceRefresh": 0,
    "isPermabanned": 0,
    "isMutebanned": 0,
    "remainingBanHours": 0,
    "banReason": "920Man Is Tuff",
    "skipAttestation": 1,
    "lastChallengeRedeemedTime_login": "1970 01/01 00:00:00",
    "lastChallengeRedeemedTime_easy": "1970 01/01 00:00:00",
    "lastChallengeRedeemedTime_hard": "1970 01/01 00:00:00",
    "pendingMessages": ["920MAN"],
    "loginStreakData": {"length": 1, "currentTier": "diamond", "nextTierThreshold": 3, "nextTier": "bronze"},
    "matchmakingSegment": None,
}


async def handle_login(body: dict) -> dict:
    """
    Process a login request. Auto-creates the account if it doesn't exist.
    Returns the 'data' payload (will be wrapped by the Lambda envelope).
    """
    account_id = body.get("accountID", "")
    oculus_id = body.get("oculusID", "")
    initial_skin = body.get("initialSkinColor", 0)
    initial_eye = body.get("initialEyeColor", -1)
    props_to_get = body.get("propertiesToGet", [])

    # Look up or create account
    account = await accounts.find_one({"accountID": account_id}, {"_id": 0})

    if account is None:
        # Auto-create new account from the template + admin profile.
        profile = _load_profile()
        account = dict(DEFAULT_ACCOUNT)
        account.update(profile)

        # Own every bundle currently in the database.
        account["ownedBundles"] = await _all_bundle_keys()

        account["accountID"] = account_id
        account["displayName"] = oculus_id or account_id
        # Client-supplied colours only apply when the profile leaves them unset.
        if "skinColor" not in profile:
            account["skinColor"] = initial_skin
        if "eyeColor" not in profile:
            account["eyeColor"] = initial_eye
        account["firstLogin"] = _server_time()
        await accounts.insert_one({**account})
        print(f"[login] Created new account: {account_id} ({oculus_id}) "
              f"bundles={len(account['ownedBundles'])} "
              f"roles={len(account.get('roleKeys', []))}")
    else:
        print(f"[login] Existing account: {account_id}")

    # Build response from the full account payload to match legacy behavior.
    # Older clients often tolerate/expect additional fields beyond
    # propertiesToGet, so we include all known account fields.
    data = {k: v for k, v in account.items() if k != "accountID"}

    # Ensure requested properties always exist.
    for prop in props_to_get:
        if prop not in data:
            data[prop] = default_for_property(prop)

    # Always include session/auth fields
    data["serverTime"] = _server_time()
    data["gameSessionID"] = "52759867"
    data["publicSessionID"] = "64827527"
    data["challengeNonce"] = "-4DJfVUq6G0_glnZzeV8ng=="
    data["skipAttestation"] = 1
    data["accessKey"] = ACCESS_KEY
    data["secretKey"] = SECRET_KEY
    data["sessionToken"] = "IQoJb3JpZ2luX2VjEKT//////////wEaCXVzLXdlc3QtMSJGMEQCIGux7ko80bOc/A6uIGmqpS30/lrR+BnmX4MOvh3/QILuAiAOBM/D4cVQN6p6JJZOpkufXsa2kcGbsn2ugIADV6Py7yrHAgh9EAMaDDY3MzQ5MzU2Mzk1NSIMlwPaIA+3J2hs9HXxKqQC8uRuzR0yjH65TFEOvzruUIo3FKIK+1n8JkDY1ocNpJM2dbFhvO/8DCXd0P44OG/RF7H5CkMsr5M4S5GAf9AZfZrrGakyTQlfJDX3AElzIjci1h5FRdMtjxZxXTUze/A05r8q7giQ9p6AA3ztE0aQTQcHNMK3VoAU1dbr/+Vb/ctvGVNL8ghoXLPnkIy3/ACHxtZie1VwtmVeTJ3bbrGdjIET8PlIIH4RerAbALwOH54NVln4sWFduZWLMWSKKs65WoEwXRfaShzIsMnDzZqUK/P6Q3ZmtnKpD/1gM2sWF+zYcnj8r4chdROpXHWteaF7sB5JGGepetVAkZlbgDxo3gVIQXwL4WaXKjl8iyPD1hBPo+WQAt2qlTtmfR5ps8qhUZ956zD0yMa7BjrYAeGmBxUhgipjxgcVGnsNqU4a9CKP9l4FYWsVR4c6JqkNllSXG0AklAqGUBAcD5iBiPef0lGsugjCkbINfFNWIn4MMbM4Ez0O34YSpJL9hGjOFzz8RtWdH6eRlQmc3QPttj9LaQKNXrnyl7ibTikRLGMI2+m3ha0/nG8Ytx4iHIKLzGfYGNGlOLcVWJ1ehekkMpUAY7IdOYupiz4ZUByuWye32O9i8hXUVW14b6bGaN4IgDIwFKqOQkgE+UIn4XFfhrNUK8qhrPNj+7MuLvNUmzdQzPcJ4J1ERQ=="
    data["e_accessKey"] = "eRi9T0nMr6NzYfPn9atAYRULSDLM5hy5jzcjiDRO/x4wvzjE6/kjFW5Ygj1EupKZ"
    data["e_secretKey"] = "9YuDOxB0EHRYW0xu4OFzg5bMabZuV4U8fcTE7TVrJBsQfm16Ld0Ld0KJHjGP7758hb0uEznFuUjD2BS7caBnm66ThP4/27+FV6QVCqJOZziqwchMdagxogbQIDOKYG2P"


    result = {"data": data}
    _append_login_log(body, result)
    return result
